### PR TITLE
update: added abstract API for model, created 2 new projects, updated…

### PR DESCRIPTION
**Pull request by Skandharoots**
I created two separate projects for Model and View Model.
Added an API for Model and a factory method.
Migrated View Model to a new project and referenced only the API of Model to it.
Prepared View Model for independent testing using dependency injection design pattern.
I updated the View Project to ".net Standard 6.0 (LTE)", so that there are no compatibility issues with referencing View Model to View.
All projects in TP.GraphicalData are now in ".net Standard 6.0 (LTE)

Marek Kopania
234760
Information Technology

### CODE REVIEW

**Comment by mpostol** [comment]
@Skandharoots - thanks for pr. It will be reviewed very soon.

**Review by mpostol — CHANGES_REQUESTED** [review]
@Skandharoots - please pr to the GD branch but not to master.  There are too many modifications to review all of them using pr.

**Comment by Skandharoots** [comment]
@mpostol - Should I spread my changes into separate commits and pull requests?

**Comment by mpostol** [comment]
@Skandharoots  - no; it is OK, I will review the code on the branch and give you feedback.  I have just merged your proposal.  Kee it closed.

**Pull request closed without merging**
